import fs from "node:fs";
import fsp from "node:fs/promises";
import path from "node:path";

const SECTION_ORDER = ["operating_policy", "project_fact", "decision", "episodic", "task_state"];
const SECTION_TITLES = {
  operating_policy: "Operating Policies", project_fact: "Project Facts",
  decision: "Decisions", episodic: "Episodic Memory", task_state: "Task State",
};
const COLUMNS = `id, agent_id, session_key, kind, status, subject_key, canonical_key, access_scope, content, structured_payload, evidence, confidence, source_type, source_ref, created_by, accepted_by, policy_version, valid_at, decay_at, supersedes_memory_id, created_at`;

export function listRecords(db) {
  return db.prepare(
    `SELECT ${COLUMNS} FROM memories WHERE status = 'active'
       AND (decay_at IS NULL OR decay_at > strftime('%Y-%m-%dT%H:%M:%fZ','now'))
     ORDER BY
       CASE kind WHEN 'operating_policy' THEN 0 WHEN 'project_fact' THEN 1 WHEN 'decision' THEN 2 WHEN 'episodic' THEN 3 WHEN 'task_state' THEN 4 ELSE 5 END ASC,
       confidence DESC, created_at DESC, canonical_key ASC, id ASC`
  ).all();
}

export function buildContent(records) {
  const lines = ["# Governed Memory", "", "> Generated by the Librarian service. Do not edit.", ""];
  if (records.length === 0) {
    lines.push("_No active governed memories._", "");
    return lines.join("\n");
  }

  const grouped = new Map();
  for (const kind of SECTION_ORDER) grouped.set(kind, []);
  for (const r of records) { grouped.get(r.kind)?.push(r); }

  for (const kind of SECTION_ORDER) {
    const entries = grouped.get(kind) ?? [];
    if (entries.length === 0) continue;
    lines.push(`## ${SECTION_TITLES[kind]}`, "");
    for (const e of entries) {
      const heading = (e.canonical_key || e.subject_key || e.id).trim();
      const body = (e.content || "").replace(/\r\n/g, "\n").trim() || "_Empty._";
      lines.push(
        `### ${heading}`, "",
        `- canonical_key: \`${e.canonical_key}\``,
        `- confidence: \`${Number(e.confidence).toFixed(3)}\``,
        `- subject_key: \`${e.subject_key}\``,
        `- access_scope: \`${e.access_scope}\``,
        `- created_at: \`${e.created_at}\``,
        "", body, "",
      );
    }
  }
  return lines.join("\n");
}

export async function renderProjection(db, outputPath) {
  const resolved = path.resolve(outputPath);
  const records = listRecords(db);
  const content = buildContent(records);

  let existing = null;
  try { existing = await fsp.readFile(resolved, "utf8"); } catch (e) { if (e.code !== "ENOENT") throw e; }
  if (existing === content) return { changed: false, entryCount: records.length, outputPath: resolved };

  await fsp.mkdir(path.dirname(resolved), { recursive: true });
  await fsp.writeFile(resolved, content, "utf8");
  return { changed: true, entryCount: records.length, outputPath: resolved };
}
